### ISSUE TITLE
forgot to put 'ret' !

### ISSUE THREAD

**Issue by Supercip971** [Project-Navy/NavyOS#2]
in the file : https://github.com/Project-Navy/NavyOS/blob/master/arch/x86/memory/paging.asm
you forgot to put 'ret' at the end of the function _asm_reload_pagedir : 
```asm

[ GLOBAL _asm_reload_pagedir ]
_asm_reload_pagedir:
    mov eax, cr3 
    mov cr3, eax
```

**Comment by 0v3rl0w** [comment]
Can you do it as a PR please ?
