### ISSUE TITLE
Optimizing factorial function

### ISSUE THREAD

**Issue by JM-299792458** [Project-Navy/NavyOS#6]
The factorial function present in lib can be optimized.
Can I work on it ?

**Comment by JM-299792458** [comment]
Can I work on it ?

**Comment by d0p1s4m4** [comment]
I think you can (code is law)

**Comment by JM-299792458** [comment]
Thanks.

**Comment by Keyboard-Slayer** [comment]
Of course you can, no need to ask :sweat_smile:
