### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by JM-299792458** [Project-Navy/NavyOS#7]
![Screen Shot 2020-10-30 at 2 10 52 AM](https://user-images.githubusercontent.com/39419246/97630131-29c12c00-1a55-11eb-845a-d936a91a73dd.png)

**Comment by Keyboard-Slayer** [comment]
Hello, 

You have to clone the repo with the submodule, 
the following command should do the trick : 

```bash
git submodule init && git submodule update
```

**Comment by JM-299792458** [comment]
Works now

**Comment by Keyboard-Slayer** [comment]
Perfect :+1:

**Comment by JM-299792458** [comment]
Is there any alternative command for "parted" on mac.

**Comment by Keyboard-Slayer** [comment]
I don't know, google it :man_shrugging:
